=== arduino/arduino-pro-content/validation/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "index": {
        "type": "integer"
      },
      "beta": {
        "type": "boolean"
      },
      "title": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      },
      "authors": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "coverImage": {
        "type": "object",
        "properties": {
          "src": {
            "type": "string"
          }
        },
        "required": [
          "src"
        ]
      },
      "tags": {
        "type": "array",
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          }
        ]
      },
      "abstract": {
        "type": "string"
      },
      "previousArticle": {
        "type": ["string", "null"]
    },
    "nextArticle": {
        "type": ["string", "null"]
      }
    },
    "required": [
      "id",
      "index",
      "title",
      "slug",
      "authors",
      "coverImage",
      "tags",
      "abstract",
      "previousArticle",
      "nextArticle"
    ]
  }

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-usb/metadata.json
{
   "id":"por-ard-usb",
   "index": 4,
   "beta": true,
   "title":"Portenta H7 as a USB Host",
   "slug":"por-ard-usb",
   "authors":[
      "Jose Garcia"
   ],
   "coverImage":{
      "src":"assets/por_ard_usbh_cover.svg?sanitize=true"
   },
   "tags":[
      "USB",
      "HID",
      "RGB LED"      
   ],
   "abstract":"This tutorial teaches you how to set up the Portenta H7 to act as a USB host in a way that allows to connect peripherals such as a keyboard or mouse to interact with it.",
   "previousArticle":"por-ard-ap",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-ble/metadata.json
{
   "id":"por-ard-ble",
   "index": 1,
   "title":"BLE on the Portenta H7 For Arduino",
   "slug":"por-ard-ble",
   "authors":[
      "Jeremy Ellis",
      "Sebastian Hunkeler"
   ],
   "coverImage":{
      "src":"assets/por_ard_ble_cover.svg?sanitize=true"
   },
   "tags":[
      "BLE",
      "IDE",
      "Setup",
      "Blink"
   ],
   "abstract":"This tutorial teaches you how to run BLE on the Portenta H7 to control the on board LED using an external Bluetooth application.",
   "previousArticle":"por-ard-ap",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/vs-ard-lora/metadata.json
{
   "id":"por-ard-bl",
   "index": 6,
   "title":"Connecting the Vision Shield to TTN using LoRa",
   "slug":"vs-ard-ttn",
   "authors":[
      "Ignacio Herrera",
      "Lenard George"
   ],
   "coverImage":{
      "src":"assets/vs_ard_things_nw.svg?sanitize=true"
   },
   "tags":[
      "Things Network",
      "LoRa",
      "Vision Shield"
   ],
   "abstract":"This tutorial explains how to connect your Portenta H7 to The Things Network (TTN) using the the Vision Shield's Lora Connectivity feature.",
   "previousArticle":"",
   "nextArticle":"por-openmv-fd"
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-openmv-fd/metadata.json
{
   "id":"por-openmv-fd",
   "index": 6,
   "title":"Creating a Basic Face Filter",
   "slug":"por-openmv-fd",
   "authors":[      
      "Sebastian Romero",
      "Lenard George"
   ],
   "coverImage":{
      "src":"assets/por_openmv_fd_cover.svg?sanitize=true"
   },
   "tags":[
      "OpenMV",
      "Face Detection",
      "Haar Cascade",
      "Machine Vision",
      "Machine Learning"
   ],
   "abstract":"In this tutorial you will build a MicroPython application with OpenMV that uses the Portenta Vision Shield to detect faces and overlay them with a custom image, in this case, a smiley.",
   "previousArticle":"por-ard-bl",
   "nextArticle":null
}
