=== arduino/arduino-pro-content/validation/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "index": {
        "type": "integer"
      },
      "beta": {
        "type": "boolean"
      },
      "title": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      },
      "authors": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "coverImage": {
        "type": "object",
        "properties": {
          "src": {
            "type": "string"
          }
        },
        "required": [
          "src"
        ]
      },
      "tags": {
        "type": "array",
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string"
          },
          {
            "type": "string"
          }
        ]
      },
      "abstract": {
        "type": "string"
      },
      "previousArticle": {
        "type": ["string", "null"]
    },
    "nextArticle": {
        "type": ["string", "null"]
      }
    },
    "required": [
      "id",
      "index",
      "title",
      "slug",
      "authors",
      "coverImage",
      "tags",
      "abstract",
      "previousArticle",
      "nextArticle"
    ]
  }

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-bl/metadata.json
{
   "id":"por-ard-bl",
   "index": 6,
   "title":"Updating the Portenta Bootloader",
   "slug":"por-ard-bl",
   "authors":[
      "Sebastian Hunkeler",
      "Lenard George"
   ],
   "coverImage":{
      "src":"assets/por_ard_bl_cover.svg?sanitize=true"
   },
   "tags":[
      "Bootloader",
      "Firmware",
      "Core"            
   ],
   "abstract":"This tutorial will explain what a bootloader is, why you should consider keeping it updated and how you can update it.",
   "previousArticle":"por-openmv-bt",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-lvgl/metadata.json
{
   "id":"por-ard-gs",
   "index": 1,
   "title":"Creating GUIs With LVGL",
   "slug":"por-ard-lvgl",
   "authors":[
      "Pablo Marqu√≠nez",
      "Lenard George"
   ],
   "coverImage":{
      "src":"assets/por_ard_lvgl_cover.svg?sanitize=true"
   },
   "tags":[
      "USB Host",
      "LVGL",
      "GUI"
   ],
   "abstract":"In this tutorial you will learn to use LVGL (Light and Versatile Graphics Library) to create a simple graphical user interface that consists of a label that updates itself.",
   "previousArticle":"por-ard-kvs",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-openmv-gs/metadata.json
{
   "id":"por-openmv-gs",
   "index": 1,
   "title":"Getting started with OpenMV and MicroPython",
   "slug":"por-openmv-gs",
   "authors":[
      "Sebastian Hunkeler",
      "Benjamin Danneg√•rd"
   ],
   "coverImage":{
      "src":"assets/por_mp_gs_cover.svg?sanitize=true"
   },
   "tags":[
      "Getting Started",
      "OpenMV",
      "Setup",
      "MicroPython",
      "PWM"
   ],
   "abstract":"This tutorial teaches you how to set up the Arduino Portenta H7, how to configure your computer and how to run a MicroPython script with OpenMV.",
   "previousArticle":null,
   "nextArticle":"por-openmv-bt"
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-kvs/metadata.json
{
   "id":"por-ard-kvs",
   "index": 8,
   "title":"Creating a Flash-Optimised Key-Value Store",
   "slug":"por-ard-kvs",
   "authors":[
      "Giampaolo Mancini"
   ],
   "coverImage":{
      "src":"assets/por_ard_block_device_cover.svg?sanitize=true"
   },
   "tags":[
      "Storage",
      "Key-Value store",
      "Flash"
   ],
   "abstract":"This tutorial explains how to create a flash-optimised key-value store using the flash memory of the Portenta H7.",
   "previousArticle":"por-ard-trace32",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-iap-tdb/metadata.json
{
   "id":"por-ard-iap-tdb",
   "index": 8,
   "title":"Using the Flash on Portenta H7 - Part 2 - KeyValue Store",
   "slug":"por-ard-iap-tdb",
   "authors":[
      "Giampaolo Mancini"
   ],
   "coverImage":{
      "src":"assets/por_ard_gs_cover.svg?sanitize=true"
   },
   "tags":[
      "Storage",
      "KeyValue Store",
      "Flash"
   ],
   "abstract":"This tutorial will show you how to create a flash-optimized KeyValue Store using the flash memory of the microcontroller on the Portenta H7.",
   "previousArticle":"por-ard-iap",
   "nextArticle":"por-ard-qspif"
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-ap/metadata.json
{
   "id":"por-ard-ap",
   "index": 3,
   "title":"Portenta H7 as a Wifi Access Point",
   "slug":"por-ard-ap",
   "authors":[
      "Lenard George"
   ],
   "coverImage":{
      "src":"assets/por_ard_ap_cover.svg?sanitize=true"
   },
   "tags":[
      "WiFi", 
      "Access Point", 
      "HTTP",
      "Web Server"
   ],
   "abstract":"In this tutorial you will configure the Portenta H7 as an access point and build a simple web server that will allow you to control the built-in RGB LEDs from your mobile device.",
   "previousArticle":"por-ard-dcp",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-openmv-bt/metadata.json
{
   "id":"por-openmv-bt",
   "index": 5,
   "title":"Blob Detection with Portenta and OpenMV",
   "slug":"por-openmv-bt",
   "authors":[      
      "Sebastian Romero"
   ],
   "coverImage":{
      "src":"assets/por_openmv_bt_cover.svg?sanitize=true"
   },
   "tags":[
      "OpenMV",
      "Blob Detection",
      "Machine Vision",
      "Machine Learning"
   ],
   "abstract":"This tutorial will show you how to use the vision carrier board for Portenta to detect the presence and the position of objects in a camera image.",
   "previousArticle":"por-ard-ble",
   "nextArticle":null
}

=== arduino/arduino-pro-content/content/tutorials/portenta-h7/por-ard-trace32/metadata.json
{
   "id":"por-ard-trace32",
   "index": 7,
   "title":"Setting Up Portenta H7 For Arduino",
   "slug":"por-ard-trace32",
   "authors":[
      "Marco Ferrario", 
      "Lauterbach Italy", 
      "Sebastian Romero"
   ],
   "coverImage":{
      "src":"assets/por_ard_trace32_cover.svg?sanitize=true"
   },
   "tags":[
      "Debugging",
      "Lauterbach",
      "TRACE32"      
   ],
   "abstract":"This tutorial will show you how to use the Lauterbach TRACE32 GDB front-end debugger to debug your Portenta H7 application via GDB on a serial interface.",
   "previousArticle":"por-openmv-fd",
   "nextArticle":null
}
